### PR TITLE
feat: add atlantic-night theme

### PR DESCRIPTION
**Pull request by mrpbennett**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

This includes the [Atlantic Night](https://marketplace.visualstudio.com/items?itemName=mrpbennett.atlantic-night) theme into the theme directory for fig

### CODE REVIEW

**Review by fedeci — CHANGES_REQUESTED** [review]
Can you remove the .DS_Store file that got committed please?

**Comment by mrpbennett** [comment]
How can I remove this without adding a `.gitignore` into my commit?

**Comment by fedeci** [comment]
For sure you can add a .gitignore and it would be really welcomed!
However you will still need to run `git rm .DS_Store`.

**Comment by mrpbennett** [comment]
Finally manage to remove it :D

**Review by fedeci — APPROVED** [review]
Thanks!

**Pull request merged**
